import { UserProvider } from "@/context/AuthContext";
import "./globals.css";
import TanstackQueryProvider from "@/components/partials/TanstackQueryProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <UserProvider>
        <TanstackQueryProvider>
          <body
            className={`antialiased font-custom`}
          >
            {children}
          </body>
        </TanstackQueryProvider>
      </UserProvider>
    </html>
  );
}
